name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: |
          python train.py
          test -f models/breast_cancer_pipeline.joblib
          test -f models/feature_names.json

      - name: Run unit tests
        run: |
          pytest -q

      - name: Build Docker image
        run: |
          docker build -t bc-api:latest .

      - name: Basic endpoint tests in container
        run: |
          docker run -d -p 8000:8000 --name bc-api bc-api:latest
          sleep 5
          curl -s http://localhost:8000/ | grep -q '"status":"ok"'
          docker rm -f bc-api

      # Docker Hub push if secrets provided
      - name: Login to Docker Hub 
        if: ${{ secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD }}
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag bc-api:latest ${{ secrets.DOCKER_USERNAME }}/bc-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/bc-api:latest
